/**
 * Generated by orval v6.6.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 1.0
 */
export interface WeatherForecast {
  id?: number;
  date?: string;
  temperatureC?: number;
  readonly temperatureF?: number;
  summary?: string | null;
}

