/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 1.0
 */
import axios,{
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery,
  useMutation,
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from 'react-query'
import type {
  ViewInvoiceDto,
  Bill
} from '../api.schemas'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AsyncReturnType<
T extends (...args: any) => Promise<any>
> = T extends (...args: any) => Promise<infer R> ? R : any;


export const getApiInvoice = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ViewInvoiceDto[]>> => {
    return axios.get(
      `/api/Invoice`,options
    );
  }


export const getGetApiInvoiceQueryKey = () => [`/api/Invoice`];

    
export const useGetApiInvoice = <TData = AsyncReturnType<typeof getApiInvoice>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getApiInvoice>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetApiInvoiceQueryKey();

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getApiInvoice>> = () => getApiInvoice(axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getApiInvoice>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}

export const getApiInvoiceInvoiceId = (
    invoiceId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ViewInvoiceDto>> => {
    return axios.get(
      `/api/Invoice/${invoiceId}`,options
    );
  }


export const getGetApiInvoiceInvoiceIdQueryKey = (invoiceId: string,) => [`/api/Invoice/${invoiceId}`];

    
export const useGetApiInvoiceInvoiceId = <TData = AsyncReturnType<typeof getApiInvoiceInvoiceId>, TError = AxiosError<unknown>>(
 invoiceId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getApiInvoiceInvoiceId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetApiInvoiceInvoiceIdQueryKey(invoiceId);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getApiInvoiceInvoiceId>> = () => getApiInvoiceInvoiceId(invoiceId, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getApiInvoiceInvoiceId>, TError, TData>(queryKey, queryFn, {enabled: !!(invoiceId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}

export const getApiInvoicePaymentInvoiceId = (
    invoiceId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axios.get(
      `/api/Invoice/payment/${invoiceId}`,options
    );
  }


export const getGetApiInvoicePaymentInvoiceIdQueryKey = (invoiceId: string,) => [`/api/Invoice/payment/${invoiceId}`];

    
export const useGetApiInvoicePaymentInvoiceId = <TData = AsyncReturnType<typeof getApiInvoicePaymentInvoiceId>, TError = AxiosError<unknown>>(
 invoiceId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getApiInvoicePaymentInvoiceId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetApiInvoicePaymentInvoiceIdQueryKey(invoiceId);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getApiInvoicePaymentInvoiceId>> = () => getApiInvoicePaymentInvoiceId(invoiceId, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getApiInvoicePaymentInvoiceId>, TError, TData>(queryKey, queryFn, {enabled: !!(invoiceId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}

export const postApiInvoiceConfirmationToken = (
    token: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `/api/Invoice/confirmation/${token}`,undefined,options
    );
  }



    export const usePostApiInvoiceConfirmationToken = <TError = AxiosError<unknown>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof postApiInvoiceConfirmationToken>, TError,{token: string}, TContext>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      


      const mutationFn: MutationFunction<AsyncReturnType<typeof postApiInvoiceConfirmationToken>, {token: string}> = (props) => {
          const {token} = props || {};

          return  postApiInvoiceConfirmationToken(token,axiosOptions)
        }

      return useMutation<AsyncReturnType<typeof postApiInvoiceConfirmationToken>, TError, {token: string}, TContext>(mutationFn, mutationOptions)
    }
    export const getApiInvoiceInvoiceInvoiceId = (
    invoiceId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Bill>> => {
    return axios.get(
      `/api/Invoice/invoice/${invoiceId}`,options
    );
  }


export const getGetApiInvoiceInvoiceInvoiceIdQueryKey = (invoiceId: string,) => [`/api/Invoice/invoice/${invoiceId}`];

    
export const useGetApiInvoiceInvoiceInvoiceId = <TData = AsyncReturnType<typeof getApiInvoiceInvoiceInvoiceId>, TError = AxiosError<unknown>>(
 invoiceId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getApiInvoiceInvoiceInvoiceId>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetApiInvoiceInvoiceInvoiceIdQueryKey(invoiceId);

  

  const queryFn: QueryFunction<AsyncReturnType<typeof getApiInvoiceInvoiceInvoiceId>> = () => getApiInvoiceInvoiceInvoiceId(invoiceId, axiosOptions);

  const query = useQuery<AsyncReturnType<typeof getApiInvoiceInvoiceInvoiceId>, TError, TData>(queryKey, queryFn, {enabled: !!(invoiceId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}

